### ISSUE TITLE
PIP distribution?

### ISSUE THREAD

**Issue by kburnik** [anthony-tuininga/cx_Logging#1]
Any chance we may get this on PIP?

**Comment by anthony-tuininga** [comment]
Yes, there is a chance! I'll do that as soon as I have an opportunity to do so.

**Comment by kburnik** [comment]
Awesome! This is currently the only thing preventing me from using the Windows service wrapper from cx_freeze. Much appreciated. Cheers!

**Comment by anthony-tuininga** [comment]
Ok. This has (finally!) been done.
